### ISSUE TITLE
安卓包升级，签名不同的问题

### ISSUE THREAD

**Issue by 8XftiB** [KNKPA/KNKPAnime#11]
安卓13，每次安装新版本都提示签名不一致，需要卸载再安装，不是很方便

**Comment by songbirdzz** [comment]
是的，之前没考虑太多更新相关的东西。下个版本会尝试加一个安卓的更新库。

**Comment by songbirdzz** [comment]
Hello! 今天试着给安卓的包更新了一下签名相关的东西，请问你有时间试一下还有没有签名相关的问题吗？具体来说，在[这个页面](https://github.com/KNKPA/KNKPAnime/releases/tag/1.0.0)下载两个不同的apk，试试能不能更新。
这两个版本的区别是，`.1.apk`的设置页面里没有版本号，`.3.apk`中设置页面有版本号。
如果能帮忙一下的话就太好了w

**Comment by 8XftiB** [comment]
可以正常安装更新了，谢了
