### ISSUE TITLE
希望可以加入简体中文的资源

### ISSUE THREAD

**Issue by canmeng0110** [KNKPA/KNKPAnime#12]
希望可以加入简体中文的资源，跪求。

**Comment by songbirdzz** [comment]
这个看视频原网站的，如果你有比较好的网站可以分享一下，我加进去。

**Comment by canmeng0110** [comment]
我目前只找到两个简体的视频网站
不能直连：
https://www.libvio.pw/
直连：
https://www.nyafun.net/
希望可以帮到你。一般比较好的资源都是磁力链接或者RSS订阅，我不懂技术，所以也不知道能用上不，需要的话我整理发出来。

**Comment by songbirdzz** [comment]
第一个我看看能不能加，第二个这种网站我见过好多类似的，我怀疑都是一个模子里套出来的...

**Comment by canmeng0110** [comment]
虽然长得一样，但就我收藏的网站来看，里面资源好像不太一样，就是长得像，内容不一样。

**Comment by songbirdzz** [comment]
soga 知道了。

**Comment by songbirdzz** [comment]
libvio试着加了一下，重新开一下软件应该就能看到了

**Comment by canmeng0110** [comment]
好像不太行
显示：Null check operator used on a null value
同个网络环境下其他可以正常播放的，换直连也是不行，一直显示这个错误

**Comment by songbirdzz** [comment]
我猜是和网络有关，你也提到这个网站不能直连。我这边就能正常打开= =

**Comment by songbirdzz** [comment]
nyafun加了，不过需要从预览版里下载新版本。

**Comment by canmeng0110** [comment]
真的十分感谢，辛苦大大。

**Comment by songbirdzz** [comment]
对了，现在应该还在跑编译，得过十几二十分钟才能更新出来（
那我就关issue了
