### ISSUE TITLE
希望可以增加几个新功能

### ISSUE THREAD

**Issue by Sakeaa** [KNKPA/KNKPAnime#13]
1.历史记录中加上“喜欢”按钮
目前只有删除选项，还得先搜索然后点喜欢
<img width="951" alt="5d4789aa5efe3d40d34955968baa9d45" src="https://github.com/KNKPA/KNKPAnime/assets/147962255/9125e41f-2698-4434-bc9d-5bf8f7d75146">

2.全屏后隐藏右边选集栏(设置可勾选)
每次全屏后还要手动关掉;w;
<img width="1280" alt="9a8b9de71d416df41efc98e31cf28079" src="https://github.com/KNKPA/KNKPAnime/assets/147962255/cc2261ee-1cc4-476d-bc1c-1b043b1fdfbe">

3.在暂停按钮右方加上“下一集”按钮
不想看ED直接跳过（）

**Comment by songbirdzz** [comment]
1实现不了，喜欢是基于bangumi的数据，但是历史记录这个是基于各个视频源的，这两个不互通。
2、3应该都ok。

**Comment by Sakeaa** [comment]
> 1实现不了，喜欢是基于bangumi的数据，但是历史记录这个是基于各个视频源的，这两个不互通。 2、3应该都ok。

如果可以的话，能再加个记忆弹幕开关状态就更好了（

**Comment by songbirdzz** [comment]
done
