### ISSUE TITLE
字体问题，现在默认显示的是字体的日文变体

### ISSUE THREAD

**Issue by viruscamp** [KNKPA/KNKPAnime#15]
字体问题，现在默认显示的是字体的日文变体

**Comment by songbirdzz** [comment]
之前用的就是默认字体= =
现在的预览版还会这样吗

**Comment by viruscamp** [comment]
现在用的是 windows-1.1.1 ，搜索界面和弹幕能看出是日文变体，字体名我看不出来。
![image](https://github.com/KNKPA/KNKPAnime/assets/5574216/9e096013-beac-4d24-8708-c3d771c926ee)

**Comment by viruscamp** [comment]
现在用的是 windows-1.1.1 ，搜索界面和弹幕能看出是日文变体，字体名我看不出来。
![image](https://github.com/KNKPA/KNKPAnime/assets/5574216/9e096013-beac-4d24-8708-c3d771c926ee)

**Comment by viruscamp** [comment]
我在 win10 和 win11 上都试 1.1.1 这个问题是一样的。

这个截图是非常奇怪的，“门”字，搜索栏是异体，第一条 《绝世唐门》是标题异体，简介简体。第二条《郑义门》是标题简体，简介异体。再后面的标题简介都是异体的。

**Comment by viruscamp** [comment]
17,18年大概是日本人报汉字是简体字形，https://github.com/flutter/flutter/issues/12576  https://github.com/flutter/flutter/issues/16870  后面 flutter 说修好了。

22年开始中国人报汉字是日文字形，flutter 那边的修好是糊弄吧。

还好有人提供解决方案， https://github.com/flutter/flutter/issues/103811#issuecomment-1199012026

**Comment by songbirdzz** [comment]
刚试了一下改了全局的locale，但好像没什么用。
https://github.com/KNKPA/KNKPAnime/releases/tag/latest
这里我改了字体，应该可以改过来了。

**Comment by viruscamp** [comment]
> 刚试了一下改了全局的locale，但好像没什么用。 https://github.com/KNKPA/KNKPAnime/releases/tag/latest 这里我改了字体，应该可以改过来了。

这个字体是对的。

但我建议用 notoSansSc 而不是 notoSerifHk 。

**Comment by songbirdzz** [comment]
已经改了的话就先不改了，要是有兴趣可以提个选字体的PR。
