### ISSUE TITLE
新版本不支持系統字體了

### ISSUE THREAD

**Issue by NeKoOuO** [KNKPA/KNKPAnime#17]
導致整個介面變得非常怪
![Screenshot_2024-06-06-01-22-02-327_com.example.knkpanime.jpg](https://github.com/KNKPA/KNKPAnime/assets/111511925/1632e58d-6000-4d08-b02f-5362abc20d05)

**Comment by songbirdzz** [comment]
这个是为了解决 https://github.com/KNKPA/KNKPAnime/issues/15 而设置的app内的字体，如果不设置的话在Windows上字体会看着很奇怪。你有什么看法或建议吗？

**Comment by NeKoOuO** [comment]
這有辦法不同平台分開嗎

或者說換字體有辦法解決嗎

**Comment by songbirdzz** [comment]
我试试能不能添加一个换字体的选项，不能的话可能会改成仅Windows设为指定字体。

**Comment by songbirdzz** [comment]
新版已填加
