### ISSUE TITLE
UI 比例過於怪

### ISSUE THREAD

**Issue by NeKoOuO** [KNKPA/KNKPAnime#18]
搜尋結果不需要佔那麼多比例
![Screenshot_2024-06-06-01-26-49-655_com.example.knkpanime.jpg](https://github.com/KNKPA/KNKPAnime/assets/111511925/26da20c5-0acd-46ef-9db4-979740120ac2)

**Comment by songbirdzz** [comment]
yes I see. 后续会调整一下比例。
