### ISSUE TITLE
Pre-release版Windows端，无法打开

### ISSUE THREAD

**Issue by twodoging** [KNKPA/KNKPAnime#21]
下载了Pre-release版，系统是win11。即使用管理员模式也是打不开。

**Comment by songbirdzz** [comment]
需要更多信息，可以截图看看吗？

**Comment by twodoging** [comment]
> 需要更多信息，可以截图看看吗？

连应用程序都进不去，如何截图呢。无论怎么点击都不行。我下载了最新发布版，可以正常使用。

**Comment by Predidit** [comment]
这个问题是存在的。我在自己的项目中遇到了同样的问题。

和之前macOS构建的问题类似，本地构建的二进制文件可以正常运行，但是github actions构建的文件不行。

我尝试使用本地构建中和 media_kit 相关的dll替换 github actions 的对应的 dll。这修复了问题。

所以我想我们可以确认问题来自 media_kit。

media_kit 现在缺乏维护，相关问题长久得不到回复与解决，可能与此相关的是 media_kit/media_kit#889 media_kit/media_kit#892 

换用其他媒体库能解决问题。亦或是放弃使用 github actions 进行 windows 平台的构建。
