### ISSUE TITLE
"使用系统默认字体"设置在重启后失效

### ISSUE THREAD

**Issue by IceTeaManiac** [KNKPA/KNKPAnime#23]
在设置页面，手动开启“使用系统默认字体”选项后系统字体会生效，重启后发现字体又恢复成了原来的衬线字体。

`adaptive_theme` 这个包目前在持久化主题配置时，看起来只存储了当前使用的主题是“亮色”还是“暗色”（[L38](https://github.com/BirjuVachhani/adaptive_theme/blob/2d736832b786c2ba0f3d8178a538680d4917790b/lib/src/adaptive_theme_preferences.dart#L38)），没有存储主题具体的配置内容。为了让用户的字体设置在重启后生效，貌似还需要手动根据用户的设置去决定 [textTheme](https://github.com/KNKPA/KNKPAnime/blob/e14c3356ec8f7b13a9c751eaadf1bc2a04aee2c7/lib/app_widget.dart#L34) 是否为 `null`。

**Comment by songbirdzz** [comment]
oops，应该是在启动的时候没有使用设置信息，直接用的内置字体。忘了改那里了。
感谢反馈！
