### ISSUE TITLE
exe无法打开

### ISSUE THREAD

**Issue by Cheosxoa** [KNKPA/KNKPAnime#24]
1.1.3的exe可以正常打开，1.1.4和pre的exe仅仅在第一次打开时提示"Microsoft Defender Smartscreen阻止启动"
![屏幕截图 2024-07-20 011601](https://github.com/user-attachments/assets/273b2222-5dec-49ac-80be-30f714facdcd)
但是我已经点击仍要运行仍然无法打开，不论多次尝试都没有效果，管理员启动同上.我是计算机盲求大佬给解

**Comment by songbirdzz** [comment]
https://github.com/KNKPA/KNKPAnime/issues/21 可能和这个问题有关... 
我刚才在本地编译了一份后替换掉了原来的release，能麻烦你试一试新的能否打开吗？

**Comment by Cheosxoa** [comment]
谢谢，等空了我试试

**Comment by Cheosxoa** [comment]
可以的，已经能打开了😊👍🤓
