### ISSUE TITLE
Windows下运行 1.1.4 崩溃

### ISSUE THREAD

**Issue by mokurin000** [KNKPA/KNKPAnime#26]
```text
CPU: i7-12700H
OS: Windows 11 22631.3880
```

![image](https://github.com/user-attachments/assets/6ecce525-e925-4dd3-9848-f1ebce78d254)

崩溃发生于 libmpv-2.dll 中，除0错误

**Comment by songbirdzz** [comment]
播放所有视频都这样，还是特定视频才会崩？

虽然看起来并不是我这边能解决的问题... 不过说不定可以通过换依赖版本解决。

**Comment by mokurin000** [comment]
> 播放所有视频都这样，还是特定视频才会崩？
> 
> 虽然看起来并不是我这边能解决的问题... 不过说不定可以通过换依赖版本解决。

换了很多视频测试都会这样
奇怪的是我用FeelUOwn播放视频不会崩溃，虽然把他们的mpv-1.dll（其实是2，路径写死了）过来还是会一样devide by zero
另一个奇怪的是这个Syscall在微软文档写明，Win7以后固定返回非0

**Comment by mokurin000** [comment]
嗯。。跑了一半看到x64dbg里面进 mpv-1.dll
想起来 System32 里有个 mpv-1.dll
删掉之后KNKPAnime正常了
