### ISSUE TITLE
关于夜间模式

### ISSUE THREAD

**Issue by Qing-Novel** [KNKPA/KNKPAnime#28]
请问后续有给软件添加跟随系统变化夜间模式吗？

**Comment by songbirdzz** [comment]
可以有

**Comment by Qing-Novel** [comment]
> 可以有

好的好的，坐等作者更新了

**Comment by songbirdzz** [comment]
Implemented in https://github.com/KNKPA/KNKPAnime/commit/65b02bd95668b3c169122248740762434f260902
