### ISSUE TITLE
考虑加入 webview 支持以方便扩展编写

### ISSUE THREAD

**Issue by Predidit** [KNKPA/KNKPAnime#3]
在过去的几个小时里，我在尝试编写[ 蚂蚁影视 ](https://www.mayiyingshi.tv/)的扩展接口

这是一个很棒的视频站点，同时提供流行影视剧和番剧资源，我希望它可以代替 `lfy`

但是这个站点的鉴权相当复杂，是我之前在另一个讨论里提到的类似 `云解析的方案` 

视频资源通过 `iframe` 标签引用一个外部的带有 `javascript` 鉴权的页面实现，这个页面的脚本非常复杂并经过混淆

在参考了一些类似第三方APP的代码后，我觉得引入 `webview` 组件可以大大减少扩展接口编写的心智负担，主流的 `webview` 库均提供了向页面注入脚本的方法，我们可以不在前台显示 `webview`, 但是通过它来直接访问带有视频的页面，并通过注入的脚本直接获取 `video`标签的内容。然后将其传递给 `media_kit`。

可能的缺点主要是，增加了复杂度，并会导致更长的视频加载时间。

**Comment by Predidit** [comment]
我觉得大家都应该看看这种离大谱的接口。

![20240506175331](https://github.com/KNKPA/KNKPAnime/assets/34627277/2931d090-5243-4a6d-b428-6aa957e5afd6)

**Comment by songbirdzz** [comment]
我试了一下，应该是可以直接拿到视频资源链接的，没看到被混淆了的js。在请求的第一个html里可以拿到`player_data`，后面直接发几个请求解析一下字符串就行了。不过他们可能屏蔽了国外的ip，我试不了能不能正常播放。

不过有些网站确实用了wasm来算token，这种可能就得跑webview了。可以加个设置选择是否用使用webview的adapter。

**Comment by Predidit** [comment]
使用 `player_data` 里的数据拼接得到的那个端口号为 `8443` 的URL不是视频资源链接，是一个带有混淆过的js的页面，这个页面的js会生成下一步请求的凭据，并将返回的视频资源URL直接传递给这个页面内部的播放器。直接将这个链接传给`media_kit`是不能正常播放的，而不是网络问题导致的不能播放。

这个做法与樱花动漫类似，我提交了一个完成樱花动漫接口的PR #4

这个PR里有相关的逆向实现，也可以一窥编写这种接口的复杂度。

本着让更多人参与编写接口的想法，如果你觉得加入 webview 是可以接受的话，可以在后续引入 `webview_flutter` 和 `webview_windows` 这两个库。`webview_windows` 库如果可以的话，建议引用我仓库里的那个分支，相较于原版，添加了获取 `cookie` 的方法。

**Comment by songbirdzz** [comment]
8443请求的那个html里有一个script，明文写着播放链接：

<img width="786" alt="Screenshot 2024-05-06 at 21 57 20" src="https://github.com/KNKPA/KNKPAnime/assets/165868972/21b666b4-997b-47e5-918b-8d1881e3016c">

总之路径大概就是 播放页面的html -> `player.js` -> `this.Path + this.PlayFrom + .js` -> 8443请求的html里的script tag

**Comment by Predidit** [comment]
这个数据我们正常手段根本拿不到啊。这个页面应该是js执行之后的最终输出？我们并没有执行 js 的能力。

这个页面原始的样子应该是这样的。

![20240507131723](https://github.com/KNKPA/KNKPAnime/assets/34627277/69703b28-c223-4053-82ca-606c1c3b4c0f)

**Comment by songbirdzz** [comment]
... 你试试`https://zj.sp-flv.com:8443/?url=mayi_e388e4HQ07U6QCU%2FJwrXaX%2BhmgItLoF2SgL86uV3Ps7dXnflXicL6i0kEdNGjbtp5SIza4l4RsLieiBbTf66%2FzZpd8XmUUUZJ9M`

我curl都拿得到= =

**Comment by Predidit** [comment]
我知道是什么原因造成我们测试的差异了。

这个站点不同视频资源的接口是不一样的，格式为 `zj.sp-flv.com:8443` 的接口不需要鉴权，格式为 `vip.sp-flv.com:8443` 的接口有极为复杂的鉴权。

我试了你的那个链接，直接可以获得资源链接。

但是你可以试试我这个 `https://vip.sp-flv.com:8443/?url=mayi_2e75BsWXgBrgKoKqss6KVl76TBC4iNxoJKjktduEFQYpq8uE%2FCMRblMAQonMy6HKniiWCu5BjuFulllwUHET%2FX2OwsDA8F0sfRLjw2HHwGLTheg%2Fut8`

**Comment by songbirdzz** [comment]
确实，看到了。

说回webview，我觉得完全可以加。不过为了用着方便点，希望可以达到这些：

- [ ] 创建一个wrapper class，统一两个webview库需要用到的操作；
- [ ] 修改设置页、`AdapterSearchController`和其他需要修改的部分，使用户可以选择是否使用需要webview的adapter；
- [ ] 对于macOS，再引入一个macOS的webview库或默认禁用webview。

**Comment by Predidit** [comment]
前两条也是我想实现的。

关于 Macos 的问题，看上去用 flutter_inappwebview 库取代 webview_flutter 是不错的选择，这个库提供了除 windows 平台外的支持。

**Comment by songbirdzz** [comment]
looks good to me

**Comment by songbirdzz** [comment]
顺便问一下，你想被加到collaborater里吗？这样你可以merge自己的pr。

**Comment by Predidit** [comment]
谢谢你的邀请。

我很高兴能成为这个仓库的 collaborator。我会尽力为这个项目做出贡献的。

**Comment by songbirdzz** [comment]
邀请了，不过还是有件事想约定一下：如果要commit的话，希望可以用pr的方式提交，不要直接push到main上；feature相关的pr也等我double check一下，不过如果我长时间没回复或者紧急的修bug pr, feel free to merge.

**Comment by Predidit** [comment]
我会遵守此规则进行贡献。

分支保护功能也非常适合这种场合。

**Comment by songbirdzz** [comment]
我加了inappwebview，你想弄一下Windows的吗？

**Comment by Predidit** [comment]
我最近在尝试做类似的工作，实际上使用 `webview_windows` 库需要一些比较奇怪的实现。

这个库不支持无头模式，并且需要中页面内保持一个高度为0的控件。当此控件不存在与页面上时 (例如被替换为空白的` Container()`)。此控件相关的方法将无法使用，需要加载此控件并重新调用其自带的初始化方法。

总之会降低代码质量，并且没有办法像您之前的 `inappwebview` 相关提交那么优雅。您觉得引入还是在 `windows` 平台上禁用此特性比较好。

**Comment by songbirdzz** [comment]
您也太客气了。

我今天看了一下，其实inappwebview已经在开始支持Windows了，不过`onLoadResource`好像还没实现。也许未来可以直接用这个库就行了，就是不知道要多久才能支持。

话再说回来，写不好看的代码也是engineering的一部分... 只要封装得好看就行了。
