### ISSUE TITLE
希望windows端加入播放时置顶窗口的功能

### ISSUE THREAD

**Issue by YuzhouSky233** [KNKPA/KNKPAnime#6]
这对于做别的事刷动画的太重要了

**Comment by songbirdzz** [comment]
<img width="1224" alt="Screenshot 2024-05-08 at 06 51 06" src="https://github.com/KNKPA/KNKPAnime/assets/165868972/1c0480e1-2623-42e6-8547-f27308712feb">

在设置页面

**Comment by songbirdzz** [comment]
因为似乎只是没有找到已经有的功能，所以我先关掉这个issue了。如果你没找到/发现bug的话，可以再打开。

顺带一提，目前版本的代码里不小心把代理开关和置顶开关连到同一个变量上了，所以会导致这两个开关同开或同关，但控制的都是置顶功能。如果是这个问题就不用再开了，已经修复掉了。
