### ISSUE TITLE
关于使用上的一些建议

### ISSUE THREAD

**Issue by hiyoung3937** [KNKPA/KNKPAnime#7]
## 环境
window11 22h2
软件版本：1.0.10
### 1. 播放器全屏下无法隐藏底部任务栏
![image](https://cdn.jsdelivr.net/gh/hiyoung3937/img_hiyoung@master/外用链接/image.40gzfc2rs4o0.webp)

### 2. 弹幕源和番剧详情页建议增加关闭按钮或右键关闭（操作方式最好统一）
![image](https://cdn.jsdelivr.net/gh/hiyoung3937/img_hiyoung@master/外用链接/image.79fp5jze8nc0.webp)

![image](https://cdn.jsdelivr.net/gh/hiyoung3937/img_hiyoung@master/外用链接/image.11icoi8s68ts.webp)

**Comment by songbirdzz** [comment]
1. 我这几天手边没Windows电脑，要下周再看。不过印象里我没碰到过这种情况。
2. 我也有点觉得太大了，准备给这些窗口缩小一点，方便点击背景关闭窗口，不过暂时没打算加其他方式关闭。如果有兴趣自己加可以提pr。
3. 这是整个程序的title bar，我觉得还是关闭整个程序符合直觉。
4. 其实adapter search就是从bgm search里拆出来的😅 当时先搞了bgm search，后来发现如果bgm没有的东西就搜不出来了，于是就拆出来了个直接搜adapter的功能。bgm搜索确实有点多余，但毕竟收藏功能还要靠它，如果删掉了就只能收藏当季番了（从日历界面）。
5. 能否在具体一点？播放器界面是有一些快捷键的，只不过没有写出来，比如左右箭头快进快退、d开关弹幕、j跳过90秒（片头片尾长度）。

**Comment by axlmly** [comment]
> 1. 我这几天手边没Windows电脑，要下周再看。不过印象里我没碰到过这种情况。
> 2. 我也有点觉得太大了，准备给这些窗口缩小一点，方便点击背景关闭窗口，不过暂时没打算加其他方式关闭。如果有兴趣自己加可以提pr。
> 3. 这是整个程序的title bar，我觉得还是关闭整个程序符合直觉。
> 4. 其实adapter search就是从bgm search里拆出来的😅 当时先搞了bgm search，后来发现如果bgm没有的东西就搜不出来了，于是就拆出来了个直接搜adapter的功能。bgm搜索确实有点多余，但毕竟收藏功能还要靠它，如果删掉了就只能收藏当季番了（从日历界面）。
> 5. 能否在具体一点？播放器界面是有一些快捷键的，只不过没有写出来，比如左右箭头快进快退、d开关弹幕、j跳过90秒（片头片尾长度）。

能增加鼠标操作逻辑吗，比如双击播放暂停。
以及在全屏状态下无法唤出集数列表，齿轮设置弹窗太大太空

**Comment by songbirdzz** [comment]
鼠标操作倒是可以，明天弄一下；播放列表这个是历史遗留问题，也可以改。至于最后一个问题：

> 2. 我也有点觉得太大了，准备给这些窗口缩小一点，方便点击背景关闭窗口

**Comment by hiyoung3937** [comment]
> 1. 我这几天手边没Windows电脑，要下周再看。不过印象里我没碰到过这种情况。
> 2. 我也有点觉得太大了，准备给这些窗口缩小一点，方便点击背景关闭窗口，不过暂时没打算加其他方式关闭。如果有兴趣自己加可以提pr。
> 3. 这是整个程序的title bar，我觉得还是关闭整个程序符合直觉。
> 4. 其实adapter search就是从bgm search里拆出来的😅 当时先搞了bgm search，后来发现如果bgm没有的东西就搜不出来了，于是就拆出来了个直接搜adapter的功能。bgm搜索确实有点多余，但毕竟收藏功能还要靠它，如果删掉了就只能收藏当季番了（从日历界面）。
> 5. 能否在具体一点？播放器界面是有一些快捷键的，只不过没有写出来，比如左右箭头快进快退、d开关弹幕、j跳过90秒（片头片尾长度）。

1. 全屏不能隐藏状态栏：今天又试了一下还是一样的，不知道是不是我才有这种情况🤔
2. 关于快捷键我认为可以参考一下B站的网页端的（看番的大部分应该都常用B站吧）
     下面几个是我个人用的比较多的，可以参考一下
比如：
     - “F”键全屏、
     - “[” 和 “]” 切换上下集、
     - 左右箭头快进快退几秒（如果有长按临时倍速更好了，我个人用的还挺多）、上下箭头调节音量
     - “z”、"x"、"c"：恢复一倍速，减倍速、加倍速（这个参考potplayer的）
     - “d”开关弹幕

**Comment by songbirdzz** [comment]
thanks, 很好的快捷键建议。我平时就d用的比较多，所以现在只加了这个。

不过安卓这事... 我在模拟器上试是没问题的，但我没有真机... = =
<img width="786" alt="Screenshot 2024-05-09 at 23 29 34" src="https://github.com/KNKPA/KNKPAnime/assets/165868972/f7822002-82ba-43ea-9bf5-078036b5a245">

**Comment by songbirdzz** [comment]
上面提到的除了切换倍速之外的快捷键已经加进来了，弹幕搜索窗口也改小了，全屏下也可以开播放列表了。其他没有实现的东西应该暂时不会去改了，如果有想加的快捷键或其他功能倒是欢迎提pr。
