### ISSUE TITLE
支持Bangumi.tv账号

### ISSUE THREAD

**Issue by BTMuli** [KNKPA/KNKPAnime#8]
~~感谢该项目让我又有能借鉴的他山之玉了~~

其实追番完全可以结合Bangumi的账号数据的，结合番剧源直接使用体验超提升↑↑↑

~~挺好奇为啥同样采用 `media_kit` 我的包就这么大呢~~

**Comment by Predidit** [comment]
追番结合 Bangumi  @的账号数据应该是可以做的，不过这种比较大feature的加入应该需要仓库的主人 @songbirdzz 的同意。 

关于包的体积问题， `media_kit` 的文档里有相关的建议，原文如下

> [Enable --split-per-abi](https://docs.flutter.dev/deployment/android#what-is-a-fat-apk) or [use app bundle (instead of APK)](https://docs.flutter.dev/deployment/android#when-should-i-build-app-bundles-versus-apks) on Android.

**Comment by songbirdzz** [comment]
我不喜欢碰别人的credential，虽然说代码是开源的，但我release里完全可以传一个不是这个代码编译出来的版本。尤其是我代码里还用了我域名下的cf worker，谁知道能用来传什么呢，我自己约定一个key加密解密一下账号密码就都传过来了。
