### ISSUE TITLE
部分新番日历无视频源

### ISSUE THREAD

**Issue by macosx10** [KNKPA/KNKPAnime#9]
从新番日历进入，有部分番剧不能列出视频源，例如《怪异与少女与神隐》，前两个搜索入口进入能搜到视频源，能正常列出播放

**Comment by songbirdzz** [comment]
>需要注意的是，在”Bangumi搜索“页面搜索时，会使用Bangumi提供的番剧名以及你所输入的搜索词在各番剧源进行两次搜索；而在追番、新番日历这两个页面点击某一个番剧的时候，只会用Bangumi提供的番剧名进行一次搜索，因此可能会出现无法搜索到的情况。如果这种情况发生的话，请在两个搜索界面搜索或通过历史记录进入（如果你看过这部番的话）。

此事在readme中亦有记载
